package com.projectx.ProjectX.enums;

public enum EventType {
    CONCERT, HOUSE_PARTY, PICNIC, PARK_ACTIVITY, SPORTS_ACTIVITY, FESTIVAL, CULTURE_ACTIVITY, CONTEST,
    SHOW, OTHER, MEETING, PRESENTATION
}
