spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/project_x
    username: root
    password: root
  security:
    filter:
      order: 10
  mail:
    host: smtp.gmail.com
    port: 587
    username: project.x.mailservice65@gmail.com
    password: ProX0605Smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
jwt:
  secret: projectx